[build]
  base = "apna-shelter/"
  publish = "build"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "16.14.0"
  NPM_VERSION = "8.5.0"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  REACT_APP_API_URL = "https://apna-shelter-api.herokuapp.com"

[context.deploy-preview.environment]
  REACT_APP_API_URL = "https://apna-shelter-api-staging.herokuapp.com"
